[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "helloWorld"
authors = [{name = "DSm", email = "deansmith@anl.gov"}]
dynamic = ["version", "description"]
